version: '3.8'

services:
  pitchlense:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # Frontend
      - "8000:8000"  # Backend API
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/pitchlense
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - ENVIRONMENT=production
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - pitchlense-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=pitchlense
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pitchlense-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - pitchlense-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  pitchlense-network:
    driver: bridge
